### ISSUE TITLE
RandomSegmentsGenerator generates wrong segment count

### ISSUE THREAD

**Issue by ursusursus** [innovatrics/dot-ios-sdk-spm#1]
Not sure where and if there is a public bug tracker, but here some some thing I've encountered

1)
 `let segments = RandomSegmentsGenerator().generate(segmentCount: 5, ..)` generates 6 segments

2) 
`EyeGazeLivenessConfiguration(..., objectImageSize: CGSize(width: 30, height: 30))` does nothing to change the circle size

**Comment by jakub-vallo** [comment]
Thanks for reporting the issue, it is fixed in version 7.0.1.
