### ISSUE TITLE
Apple Privacy manifest requirement

### ISSUE THREAD

**Issue by leinhauplk** [innovatrics/dot-ios-sdk-spm#3]
Hi, will you have an updated version that meets Apple's Privacy Manifest requirement? This requirement goes into effect on May 1, 2024, which is fast approaching. -> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

I analyzed the binaries with [this script](https://github.com/Wooder/ios_17_required_reason_api_scanner, and it appears that the iface binary uses the fstat, mach_absolute_time, and stat APIs. If this is true, then a privacy manifest with API usage declarations should be created.

Thanks
Karel

**Comment by jakub-vallo** [comment]
Hi, we have just released SDK version 7.5.1. We added privacy manifests and signatures to the frameworks for which it was required.
